---
title: "Algorithmics"
author: "Ennatiqi-Mombo-Soukri"
date: "1/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data_generator <- function(n, positions, variance_values){
  library(gfpop)
  data = dataGenerator(n, positions, variance_values, type = 'variance')
  return(data)
}



css_stat <- function(y){
  stat = c()
  n = length(y)
  for(t in 1:n){
    a = sum(y[1:t]**2)/sum(y**2)
    b = t/n
    stat <- c(stat, sqrt(n/2)*abs(a-b))
  }
  return(stat)
}

binSeg <- function(s,e,y,pen=1.358){
    if (e-s==1) {
        return(c())
    } else {
        css_stats <- css_stat(y[s:e])
        cp <- which.max(css_stats) + s
        message("cp: ",cp)
        message("pen: ",pen)
        message("max(css_stats): ",max(css_stats))
        if (max(css_stats)> pen) {
            return(c(binSeg(s,cp,y,pen),cp,binSeg(cp+1,e,y,pen)))
        } else {
            return(c())
        }
    }
    
}
positions = c(0.1,0.4, 0.8, 1)
variances = c(4, 1, 5, 2)
n = 10000
y = data_generator(n, positions, variances)
pen <- 1.358 #95%
library(sys)
start_time <- Sys.time()
binSeg(1, n, y, pen)
print(Sys.time()-start_time)
```


```{r}
change_points = binSeg(1, length(y), y, pen)
k = length(variances)-1

par(mfrow=c(3,1))
plot(cumsum(y), type = 's')
abline(v=c(positions[1:k]*n, change_points), col=c(rep("blue", k),rep("red", k)), lty=c(2, 1))
plot(y, type = 's')
abline(v=c(positions[1:k]*n, change_points), col=c(rep("blue", k),rep("red", k)), lty=c(2, 1))
plot(css_stat(y), type="s")

```

```{r}
#simulation de compléxité
#function sans commentaires...
binSeg <- function(s,e,y,pen=1.358){
    if (e-s==1) {
        return(c())
    } else {
        css_stats <- css_stat(y[s:e])
        cp <- which.max(css_stats) + s
        if (max(css_stats)> pen) {
            return(c(binSeg(s,cp,y,pen),cp,binSeg(cp+1,e,y,pen)))
        } else {
            return(c())
        }
    }
}


N = 1000
y = data_generator(N, positions, variances)
start = 100
time = c()
for(i in seq(from=2, to=N, by=50)){
  start_time <- Sys.time()
  ####################
  y = data_generator(i, positions, variances)
  binSeg(1, length(y), y, pen)
  ####################
  end_time <- Sys.time()
  time = c(time, end_time-start_time)
}
plot(time)
```

