# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

css_statistic <- function(y) {
    .Call(`_variance_css_statistic`, y)
}

BS <- function(s, e, y, penality) {
    .Call(`_variance_BS`, s, e, y, penality)
}

